### ISSUE TITLE
let me join or i will mine your diamonds

### ISSUE THREAD

**Issue by AyzansAlt** [netriza/mrsdb#1]
dotn try me!!!111!!!111!!

**Comment by ItzMeWilliam** [comment]
**_TEXT ME ON DISCORD DUDE U NEVER TEXT ME CACA HEAD!!!! >:(_** @AyzansAlt well on a serious note we can work on it together on repl.it or something like that, ill invite u to the GitHub, bro :) 👍

**Comment by ItzMeWilliam** [comment]
**bb’s bf 😳#2028**

**Comment by AyzansAlt** [comment]
ik ur discord idot

**Comment by AyzansAlt** [comment]
we can go into the edit history idot @ItzMeWilliam
